/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetsRouteImport } from './routes/widgets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HablarRouteImport } from './routes/hablar'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as IndexRouteImport } from './routes/index'

const WidgetsRoute = WidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HablarRoute = HablarRouteImport.update({
  id: '/hablar',
  path: '/hablar',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/explorar': typeof ExplorarRoute
  '/gracias': typeof GraciasRoute
  '/hablar': typeof HablarRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/reader': typeof ReaderRoute
  '/settings': typeof SettingsRoute
  '/widgets': typeof WidgetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/explorar': typeof ExplorarRoute
  '/gracias': typeof GraciasRoute
  '/hablar': typeof HablarRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/reader': typeof ReaderRoute
  '/settings': typeof SettingsRoute
  '/widgets': typeof WidgetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/explorar': typeof ExplorarRoute
  '/gracias': typeof GraciasRoute
  '/hablar': typeof HablarRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/reader': typeof ReaderRoute
  '/settings': typeof SettingsRoute
  '/widgets': typeof WidgetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diario'
    | '/explorar'
    | '/gracias'
    | '/hablar'
    | '/home'
    | '/onboarding'
    | '/reader'
    | '/settings'
    | '/widgets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diario'
    | '/explorar'
    | '/gracias'
    | '/hablar'
    | '/home'
    | '/onboarding'
    | '/reader'
    | '/settings'
    | '/widgets'
  id:
    | '__root__'
    | '/'
    | '/diario'
    | '/explorar'
    | '/gracias'
    | '/hablar'
    | '/home'
    | '/onboarding'
    | '/reader'
    | '/settings'
    | '/widgets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiarioRoute: typeof DiarioRoute
  ExplorarRoute: typeof ExplorarRoute
  GraciasRoute: typeof GraciasRoute
  HablarRoute: typeof HablarRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  ReaderRoute: typeof ReaderRoute
  SettingsRoute: typeof SettingsRoute
  WidgetsRoute: typeof WidgetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widgets': {
      id: '/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof WidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hablar': {
      id: '/hablar'
      path: '/hablar'
      fullPath: '/hablar'
      preLoaderRoute: typeof HablarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiarioRoute: DiarioRoute,
  ExplorarRoute: ExplorarRoute,
  GraciasRoute: GraciasRoute,
  HablarRoute: HablarRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  ReaderRoute: ReaderRoute,
  SettingsRoute: SettingsRoute,
  WidgetsRoute: WidgetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
